% OPP(...
%    'EndFcn', @app.EndOPP, ...
%    'SynthFcn', @app.SynthesizeOPPStimuli, ...
%    'RootFolder', app.RootDataFolderEditField.Value, ...
%    'DataFile', fullfile(folder, filestem), ...
%    'VariableName', name, ...
%    'DefaultTrainingValue', trainingVal, ...
%    'DefaultTestValues', testVals ...
%    );

OPP(...
   'RootFolder', 'D:\Data\PTC\Resources', ...
   'DataFile', fullfile('C:\Data\PTC\XYZ', 'XYZ-Test'), ...
   'MeasurementType', 'test', ...
   'VariableName', 'Lprobe', ...
   'DefaultTrainingValue', 70, ...
   'DefaultTestValues', 40:-4:20 ...
   );
