<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>disable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="C462.Shared" Version="1.29.0" />
		<PackageReference Include="KLib.WindowsVoice" Version="1.2.0" />
		<PackageReference Include="naudio.winforms" Version="2.2.1" />
		<PackageReference Include="ScottPlot.WinForms" Version="5.1.59" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\OppStreamer.ConfigApi\OppStreamer.ConfigApi.csproj" />
		<ProjectReference Include="..\..\src\OppStreamer.Core\OppStreamer.Core.csproj" />
		<ProjectReference Include="..\..\src\OppStreamer.Hardware\OppStreamer.Hardware.csproj" />
	</ItemGroup>

</Project>